#!/bin/bash

DAY="$1"

if [ -z "$DAY"]; then
   echo "Usage: ./new <DAY>"
fi

DAY_DIR=$(printf "%02d" $DAY)

if [ -d "$DAY_DIR" ]; then
  echo "Day $DAY_DIR already exists"
  exit 1
fi

mkdir -p "$DAY_DIR"
touch "$DAY_DIR/example"
touch "$DAY_DIR/puzzle"
touch "$DAY_DIR/instructions.md"

cat > "$DAY_DIR/main.go" <<EOF
package main

import "fmt"

const DAY = "$DAY_DIR"
var EXAMPLE = fmt.Sprintf("%s/%s", DAY, "example")
var PUZZLE = fmt.Sprintf("%s/%s", DAY, "puzzle")

func Run(debug bool) {
	targetFile := shared.If(debug, EXAMPLE, PUZZLE)
	lines := shared.ReadLines(targetFile)
	part01(lines)
	part02(lines)
}

func part01(lines []string) {
	fmt.Println("Day XX - Part 1")
}

func part02(lines []string) {
	fmt.Println("Day XX - Part 2")
}
EOF

# Update the day number in the template
sed -i "s/Day XX/Day $DAY_DIR/g" "$DAY_DIR/main.go"

echo "Created day $DAY_DIR"
